name: Build and Release Expo App
on:
  push:
    tags:
      - 'v*'
jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
  build-expo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v3
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
      - name: 📦 Install dependencies
        run: pnpm install
      - name: 🚀 Build Android APK
        run: npx eas-cli build --platform android --local --profile development --non-interactive --output=./build-android/go-trena-dev-build.apk
      - name: 🚀 Build Web
        run: |
          npx expo export -p web
          cd dist
          zip -r ../web-build.zip .
      - name: Create output directory for iOS
        run: mkdir -p ./build-ios
      - name: 🚀 Build iOS (if on macOS runner)
        if: runner.os == 'macOS'
        run: npx eas-cli build --platform ios --local --profile development --non-interactive --output=./build-ios/go-trena-dev-build.ipa
        continue-on-error: true
      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-${{ github.ref_name }}
          path: ./frontend/build-android/*.apk
          retention-days: 7
      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-release-${{ github.ref_name }}
          path: ./frontend/web-build.zip
          retention-days: 7
      - name: Upload iOS artifact (if built)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-${{ github.ref_name }}
          path: ./frontend/build-ios/*.ipa
          retention-days: 7
